//! Module 6 - cross-platform file association and custom icons.
//!
//! `hermes install-system` teaches the desktop what a `.origin` and a `.foiled`
//! file are, gives them icons, and points double-clicks at this binary. Every
//! icon is compiled into the executable with `include_bytes!` and written out
//! at install time, so there is no installer, no asset directory to ship and
//! nothing to go missing after the binary is moved.
//!
//! All three platforms register **per-user**:
//!
//! * Windows - `HKEY_CURRENT_USER\Software\Classes` (no elevation).
//! * Linux   - `~/.local/share/{mime,applications,icons}` (FreeDesktop).
//! * macOS   - `~/Applications/Hermes.app` with `CFBundleDocumentTypes`.
//!
//! Nothing is written outside the user's own profile, and `uninstall-system`
//! reverses all of it.

use crate::paths;
use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

pub const PROGID_ORIGIN: &str = "Hermes.Origin";
pub const PROGID_FOILED: &str = "Hermes.Foiled";
// The MIME types and UTIs are the public naming contract for the type; each is
// referenced only by the platform module that speaks that dialect.
#[allow(dead_code)]
pub const MIME_ORIGIN: &str = "application/x-hermes-origin";
#[allow(dead_code)]
pub const MIME_FOILED: &str = "application/x-hermes-foiled";
#[allow(dead_code)]
pub const UTI_ORIGIN: &str = "dev.hermes.origin";
#[allow(dead_code)]
pub const UTI_FOILED: &str = "dev.hermes.foiled";
pub const DESC_ORIGIN: &str = "HERMES Origin (software source)";
pub const DESC_FOILED: &str = "HERMES Update Plan";

// ---------------------------------------------------------------------------
// Embedded icons
// ---------------------------------------------------------------------------

/// Icons live in the binary. `assets/icons` is generated by
/// `tools/gen_icons.py` from the master artwork.
mod embedded {
    #[cfg(windows)]
    pub const ORIGIN_ICO: &[u8] = include_bytes!("../assets/icons/origin.ico");
    #[cfg(windows)]
    pub const FOILED_ICO: &[u8] = include_bytes!("../assets/icons/foiled.ico");
    #[cfg(windows)]
    pub const HERMES_ICO: &[u8] = include_bytes!("../assets/icons/hermes.ico");

    #[cfg(target_os = "macos")]
    pub const ORIGIN_ICNS: &[u8] = include_bytes!("../assets/icons/origin.icns");
    #[cfg(target_os = "macos")]
    pub const FOILED_ICNS: &[u8] = include_bytes!("../assets/icons/foiled.icns");
    #[cfg(target_os = "macos")]
    pub const HERMES_ICNS: &[u8] = include_bytes!("../assets/icons/hermes.icns");

    #[cfg(target_os = "linux")]
    macro_rules! png_set {
        ($name:literal) => {
            &[
                (16u32, include_bytes!(concat!("../assets/icons/", $name, "_16.png")) as &[u8]),
                (22u32, include_bytes!(concat!("../assets/icons/", $name, "_22.png")) as &[u8]),
                (24u32, include_bytes!(concat!("../assets/icons/", $name, "_24.png")) as &[u8]),
                (32u32, include_bytes!(concat!("../assets/icons/", $name, "_32.png")) as &[u8]),
                (48u32, include_bytes!(concat!("../assets/icons/", $name, "_48.png")) as &[u8]),
                (64u32, include_bytes!(concat!("../assets/icons/", $name, "_64.png")) as &[u8]),
                (128u32, include_bytes!(concat!("../assets/icons/", $name, "_128.png")) as &[u8]),
                (256u32, include_bytes!(concat!("../assets/icons/", $name, "_256.png")) as &[u8]),
            ]
        };
    }

    #[cfg(target_os = "linux")]
    pub const ORIGIN_PNGS: &[(u32, &[u8])] = png_set!("origin");
    #[cfg(target_os = "linux")]
    pub const FOILED_PNGS: &[(u32, &[u8])] = png_set!("foiled");
    #[cfg(target_os = "linux")]
    pub const HERMES_PNGS: &[(u32, &[u8])] = png_set!("hermes");

}

#[derive(Debug, Default)]
pub struct Report {
    pub actions: Vec<String>,
    pub warnings: Vec<String>,
}

impl Report {
    fn did(&mut self, what: impl Into<String>) {
        self.actions.push(what.into());
    }
    fn warn(&mut self, what: impl Into<String>) {
        self.warnings.push(what.into());
    }
    pub fn print(&self) {
        for action in &self.actions {
            println!("  + {action}");
        }
        for warning in &self.warnings {
            println!("  ! {warning}");
        }
    }
}

/// Absolute path to this binary, which is what the OS will be told to launch.
fn current_exe() -> Result<PathBuf> {
    let exe = std::env::current_exe().context("cannot determine this executable's path")?;
    let canonical = fs::canonicalize(&exe).unwrap_or_else(|_| exe.clone());
    Ok(strip_verbatim(canonical))
}

/// Undo the `\\?\` prefix that `canonicalize` adds on Windows.
///
/// It matters here and nowhere else: `ShellExecute` - which is what runs a
/// `shell\open\command` on a double-click - does not accept verbatim paths, so
/// registering one produces an association that silently does nothing.
fn strip_verbatim(path: PathBuf) -> PathBuf {
    let text = path.to_string_lossy().to_string();
    if let Some(rest) = text.strip_prefix(r"\\?\UNC\") {
        return PathBuf::from(format!(r"\\{rest}"));
    }
    if let Some(rest) = text.strip_prefix(r"\\?\") {
        // Only for real drive paths: \\?\C:\... -> C:\...
        let mut chars = rest.chars();
        if chars.next().is_some_and(|c| c.is_ascii_alphabetic())
            && chars.next() == Some(':')
            && chars.next() == Some('\\')
        {
            return PathBuf::from(rest);
        }
    }
    path
}

/// Warn if the binary lives somewhere the association will not survive.
fn check_exe_location(exe: &Path, report: &mut Report) {
    let text = exe.to_string_lossy().to_lowercase();
    let volatile = ["\\target\\", "/target/", "\\temp\\", "/tmp/", "\\appdata\\local\\temp\\"];
    if volatile.iter().any(|frag| text.contains(frag)) {
        report.warn(format!(
            "registering {} - this looks like a build or temp directory; \
             move HERMES somewhere permanent and re-run install-system",
            exe.display()
        ));
    }
}

/// Write the embedded icons into `~/.config/hermes/icons` and return the dir.
fn extract_icons() -> Result<PathBuf> {
    let dir = paths::icons_dir()?;
    #[cfg(windows)]
    {
        write_icon(&dir, "origin.ico", embedded::ORIGIN_ICO)?;
        write_icon(&dir, "foiled.ico", embedded::FOILED_ICO)?;
        write_icon(&dir, "hermes.ico", embedded::HERMES_ICO)?;
    }
    #[cfg(target_os = "macos")]
    {
        write_icon(&dir, "origin.icns", embedded::ORIGIN_ICNS)?;
        write_icon(&dir, "foiled.icns", embedded::FOILED_ICNS)?;
        write_icon(&dir, "hermes.icns", embedded::HERMES_ICNS)?;
    }
    #[cfg(target_os = "linux")]
    {
        // Linux reads its icons straight out of the hicolor theme, which
        // `platform::install` populates; nothing extra is needed here.
    }
    Ok(dir)
}

#[allow(dead_code)]
fn write_icon(dir: &Path, name: &str, bytes: &[u8]) -> Result<PathBuf> {
    let path = dir.join(name);
    fs::write(&path, bytes).with_context(|| format!("writing {}", path.display()))?;
    Ok(path)
}

/// Register `.origin` and `.foiled` with the desktop.
///
/// `exe_override` lets `hermes install` register the copy it just placed in a
/// permanent directory rather than the binary currently running, which may be
/// sitting in `target/release` and about to be deleted by `cargo clean`.
pub fn install(exe_override: Option<PathBuf>) -> Result<Report> {
    let mut report = Report::default();
    let exe = match exe_override {
        Some(path) => path,
        None => current_exe()?,
    };
    check_exe_location(&exe, &mut report);
    let icons = extract_icons()?;
    report.did(format!("extracted icons to {}", icons.display()));
    platform::install(&exe, &icons, &mut report)?;
    Ok(report)
}

/// Undo everything `install` did.
pub fn uninstall() -> Result<Report> {
    let mut report = Report::default();
    platform::uninstall(&mut report)?;
    Ok(report)
}

// ===========================================================================
// Windows
// ===========================================================================

#[cfg(windows)]
mod platform {
    use super::*;
    use winreg::enums::{HKEY_CURRENT_USER, KEY_ALL_ACCESS};
    use winreg::RegKey;

    const CLASSES: &str = r"Software\Classes";

    /// Tell Explorer the association table changed, so icons refresh without
    /// a logout. Declared directly to avoid pulling in a Win32 crate.
    fn notify_assoc_changed() {
        const SHCNE_ASSOCCHANGED: i32 = 0x0800_0000;
        const SHCNF_IDLIST: u32 = 0x0000;
        #[link(name = "shell32")]
        extern "system" {
            fn SHChangeNotify(
                event_id: i32,
                flags: u32,
                item1: *const std::ffi::c_void,
                item2: *const std::ffi::c_void,
            );
        }
        unsafe {
            SHChangeNotify(
                SHCNE_ASSOCCHANGED,
                SHCNF_IDLIST,
                std::ptr::null(),
                std::ptr::null(),
            );
        }
    }

    fn register_progid(
        classes: &RegKey,
        progid: &str,
        description: &str,
        icon: &Path,
        command: &str,
        report: &mut Report,
    ) -> Result<()> {
        let (key, _) = classes
            .create_subkey(progid)
            .with_context(|| format!(r"creating HKCU\{CLASSES}\{progid}"))?;
        key.set_value("", &description)?;
        key.set_value("FriendlyTypeName", &description)?;
        // Explorer refuses to show a custom icon for a type it thinks is
        // "always show extension"-less; this keeps the extension visible.
        key.set_value("AlwaysShowExt", &"")?;

        let (icon_key, _) = key.create_subkey("DefaultIcon")?;
        icon_key.set_value("", &format!("\"{}\",0", icon.display()))?;

        let (command_key, _) = key.create_subkey(r"shell\open\command")?;
        command_key.set_value("", &command.to_string())?;

        let (verb_key, _) = key.create_subkey(r"shell\open")?;
        verb_key.set_value("FriendlyAppName", &"HERMES")?;

        report.did(format!(r"HKCU\{CLASSES}\{progid} -> {command}"));
        Ok(())
    }

    fn associate_extension(
        classes: &RegKey,
        extension: &str,
        progid: &str,
        report: &mut Report,
    ) -> Result<()> {
        let (key, _) = classes
            .create_subkey(extension)
            .with_context(|| format!(r"creating HKCU\{CLASSES}\{extension}"))?;
        key.set_value("", &progid)?;
        // OpenWithProgids keeps HERMES in the "Open with" list even if another
        // application later claims the default.
        let (open_with, _) = key.create_subkey("OpenWithProgids")?;
        open_with.set_value(progid, &"")?;
        report.did(format!(r"HKCU\{CLASSES}\{extension} -> {progid}"));
        Ok(())
    }

    /// The registration itself, against whichever classes key it is handed.
    /// Taking the root as a parameter keeps this exercisable by tests without
    /// touching the user's real file associations.
    fn register_all(classes: &RegKey, exe: &Path, icons: &Path, report: &mut Report) -> Result<()> {
        // `open` dispatches on the extension: a .origin is registered, a
        // .foiled is inspected. --from-shell keeps the console window up so a
        // double-click is readable.
        let command = format!("\"{}\" open \"%1\" --from-shell", exe.display());

        register_progid(
            classes,
            PROGID_ORIGIN,
            DESC_ORIGIN,
            &icons.join("origin.ico"),
            &command,
            report,
        )?;
        register_progid(
            classes,
            PROGID_FOILED,
            DESC_FOILED,
            &icons.join("foiled.ico"),
            &command,
            report,
        )?;
        associate_extension(classes, ".origin", PROGID_ORIGIN, report)?;
        associate_extension(classes, ".foiled", PROGID_FOILED, report)?;
        Ok(())
    }

    pub fn install(exe: &Path, icons: &Path, report: &mut Report) -> Result<()> {
        let hkcu = RegKey::predef(HKEY_CURRENT_USER);
        let (classes, _) = hkcu
            .create_subkey_with_flags(CLASSES, KEY_ALL_ACCESS)
            .context("opening HKCU\\Software\\Classes for writing")?;

        register_all(&classes, exe, icons, report)?;

        notify_assoc_changed();
        report.did("notified Explorer (SHChangeNotify)".to_string());
        Ok(())
    }

    pub fn uninstall(report: &mut Report) -> Result<()> {
        let hkcu = RegKey::predef(HKEY_CURRENT_USER);
        let classes = match hkcu.open_subkey_with_flags(CLASSES, KEY_ALL_ACCESS) {
            Ok(k) => k,
            Err(_) => return Ok(()),
        };

        for progid in [PROGID_ORIGIN, PROGID_FOILED] {
            if classes.delete_subkey_all(progid).is_ok() {
                report.did(format!(r"removed HKCU\{CLASSES}\{progid}"));
            }
        }

        for (extension, progid) in [(".origin", PROGID_ORIGIN), (".foiled", PROGID_FOILED)] {
            if let Ok(key) = classes.open_subkey_with_flags(extension, KEY_ALL_ACCESS) {
                // Only stand down if we are still the default handler.
                let current: std::result::Result<String, _> = key.get_value("");
                if matches!(current.as_deref(), Ok(value) if value == progid) {
                    let _ = key.set_value("", &"");
                }
                if let Ok(open_with) = key.open_subkey_with_flags("OpenWithProgids", KEY_ALL_ACCESS)
                {
                    let _ = open_with.delete_value(progid);
                }
                report.did(format!(r"released HKCU\{CLASSES}\{extension}"));
            }
        }

        notify_assoc_changed();
        Ok(())
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        /// Run the real registration against a scratch key, assert the shape
        /// Explorer needs, then remove it. Never touches Software\Classes.
        #[test]
        fn registers_progids_icons_and_commands() {
            const SCRATCH: &str = r"Software\Hermes.SelfTest";
            let hkcu = RegKey::predef(HKEY_CURRENT_USER);
            let _ = hkcu.delete_subkey_all(SCRATCH);
            let (classes, _) = hkcu
                .create_subkey_with_flags(SCRATCH, KEY_ALL_ACCESS)
                .expect("create scratch key");

            let exe = Path::new(r"C:\Program Files\Hermes\hermes.exe");
            let icons = Path::new(r"C:\Users\test\.config\hermes\icons");
            let mut report = Report::default();
            register_all(&classes, exe, icons, &mut report).expect("registration");

            let progid = classes.open_subkey(PROGID_ORIGIN).expect("progid key");
            let description: String = progid.get_value("").expect("progid default value");
            assert_eq!(description, DESC_ORIGIN);

            let icon: String = progid
                .open_subkey("DefaultIcon")
                .expect("DefaultIcon key")
                .get_value("")
                .expect("icon value");
            assert!(icon.ends_with(r#"origin.ico",0"#), "unexpected icon: {icon}");

            let command: String = progid
                .open_subkey(r"shell\open\command")
                .expect("command key")
                .get_value("")
                .expect("command value");
            assert!(command.contains("hermes.exe"), "unexpected command: {command}");
            assert!(command.contains(" open "), "unexpected command: {command}");
            assert!(command.ends_with(r#""%1" --from-shell"#), "unexpected command: {command}");

            for (extension, expected) in [(".origin", PROGID_ORIGIN), (".foiled", PROGID_FOILED)] {
                let key = classes.open_subkey(extension).expect("extension key");
                let mapped: String = key.get_value("").expect("extension default value");
                assert_eq!(mapped, expected);
                key.open_subkey("OpenWithProgids")
                    .expect("OpenWithProgids")
                    .get_value::<String, _>(expected)
                    .expect("listed in OpenWithProgids");
            }

            hkcu.delete_subkey_all(SCRATCH).expect("clean up scratch key");
            assert!(hkcu.open_subkey(SCRATCH).is_err());
        }

        /// Regression: `canonicalize` hands back `\\?\D:\...`, and a verbatim
        /// path in shell\open\command makes a double-click do nothing at all.
        #[test]
        fn registered_command_never_contains_a_verbatim_path() {
            assert_eq!(
                strip_verbatim(PathBuf::from(r"\\?\D:\Tools\hermes.exe")),
                PathBuf::from(r"D:\Tools\hermes.exe")
            );
            assert_eq!(
                strip_verbatim(PathBuf::from(r"\\?\UNC\server\share\hermes.exe")),
                PathBuf::from(r"\\server\share\hermes.exe")
            );
            // Ordinary paths are left exactly as they are.
            assert_eq!(
                strip_verbatim(PathBuf::from(r"C:\Program Files\Hermes\hermes.exe")),
                PathBuf::from(r"C:\Program Files\Hermes\hermes.exe")
            );
            assert!(!current_exe()
                .expect("current exe")
                .to_string_lossy()
                .starts_with(r"\\?\"));
        }
    }
}

// ===========================================================================
// Linux (FreeDesktop)
// ===========================================================================

#[cfg(target_os = "linux")]
mod platform {
    use super::*;
    use std::process::Command;

    fn data_home() -> Result<PathBuf> {
        if let Some(dir) = std::env::var_os("XDG_DATA_HOME").filter(|v| !v.is_empty()) {
            return Ok(PathBuf::from(dir));
        }
        Ok(dirs::home_dir()
            .context("cannot determine the home directory")?
            .join(".local")
            .join("share"))
    }

    fn mime_xml() -> String {
        format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="{MIME_ORIGIN}">
    <comment>{DESC_ORIGIN}</comment>
    <icon name="application-x-hermes-origin"/>
    <glob pattern="*.origin"/>
    <sub-class-of type="application/json"/>
  </mime-type>
  <mime-type type="{MIME_FOILED}">
    <comment>{DESC_FOILED}</comment>
    <icon name="application-x-hermes-foiled"/>
    <glob pattern="*.foiled"/>
    <sub-class-of type="application/json"/>
  </mime-type>
</mime-info>
"#
        )
    }

    fn desktop_entry(exe: &Path) -> String {
        format!(
            "[Desktop Entry]\n\
             Type=Application\n\
             Name=HERMES\n\
             GenericName=Decentralized Updater\n\
             Comment=Add and update software from a studio you trust\n\
             Exec={} open %f --from-shell\n\
             Icon=hermes\n\
             Terminal=true\n\
             Categories=System;PackageManager;Utility;\n\
             MimeType={MIME_ORIGIN};{MIME_FOILED};\n\
             NoDisplay=false\n\
             StartupNotify=false\n",
            exe.display()
        )
    }

    /// Install one icon into every hicolor size the theme spec expects.
    ///
    /// The artwork is raster, so there is no `scalable/` SVG to install; a
    /// 256px PNG is what every current desktop actually picks up.
    fn install_icon_set(
        data: &Path,
        theme_name: &str,
        context: &str,
        pngs: &[(u32, &[u8])],
        report: &mut Report,
    ) -> Result<()> {
        for (size, bytes) in pngs {
            let dir = data
                .join("icons/hicolor")
                .join(format!("{size}x{size}"))
                .join(context);
            fs::create_dir_all(&dir)?;
            fs::write(dir.join(format!("{theme_name}.png")), bytes)?;
        }
        report.did(format!("installed icon '{theme_name}' ({context})"));
        Ok(())
    }

    fn run_if_present(program: &str, args: &[&str], report: &mut Report) {
        match Command::new(program).args(args).status() {
            Ok(status) if status.success() => report.did(format!("ran {program}")),
            Ok(status) => report.warn(format!("{program} exited with {status}")),
            Err(_) => report.warn(format!(
                "{program} not found - log out and back in for the icons to appear"
            )),
        }
    }

    pub fn install(exe: &Path, _icons: &Path, report: &mut Report) -> Result<()> {
        let data = data_home()?;

        let mime_dir = data.join("mime/packages");
        fs::create_dir_all(&mime_dir)?;
        let mime_file = mime_dir.join("hermes.xml");
        fs::write(&mime_file, mime_xml())
            .with_context(|| format!("writing {}", mime_file.display()))?;
        report.did(format!("wrote {}", mime_file.display()));

        install_icon_set(
            &data,
            "application-x-hermes-origin",
            "mimetypes",
            embedded::ORIGIN_PNGS,
            report,
        )?;
        install_icon_set(
            &data,
            "application-x-hermes-foiled",
            "mimetypes",
            embedded::FOILED_PNGS,
            report,
        )?;
        install_icon_set(
            &data,
            "hermes",
            "apps",
            embedded::HERMES_PNGS,
            report,
        )?;

        let apps_dir = data.join("applications");
        fs::create_dir_all(&apps_dir)?;
        let desktop = apps_dir.join("hermes.desktop");
        fs::write(&desktop, desktop_entry(exe))
            .with_context(|| format!("writing {}", desktop.display()))?;
        report.did(format!("wrote {}", desktop.display()));

        run_if_present(
            "update-mime-database",
            &[data.join("mime").to_string_lossy().as_ref()],
            report,
        );
        run_if_present(
            "update-desktop-database",
            &[apps_dir.to_string_lossy().as_ref()],
            report,
        );
        run_if_present(
            "gtk-update-icon-cache",
            &[
                "-f",
                "-t",
                data.join("icons/hicolor").to_string_lossy().as_ref(),
            ],
            report,
        );
        Ok(())
    }

    pub fn uninstall(report: &mut Report) -> Result<()> {
        let data = data_home()?;
        let mut removed = Vec::new();

        for path in [
            data.join("mime/packages/hermes.xml"),
            data.join("applications/hermes.desktop"),
        ] {
            if fs::remove_file(&path).is_ok() {
                removed.push(path);
            }
        }

        for name in [
            "application-x-hermes-origin",
            "application-x-hermes-foiled",
            "hermes",
        ] {
            for size in [16, 22, 24, 32, 48, 64, 128, 256] {
                for context in ["mimetypes", "apps"] {
                    let p = data
                        .join("icons/hicolor")
                        .join(format!("{size}x{size}"))
                        .join(context)
                        .join(format!("{name}.png"));
                    let _ = fs::remove_file(p);
                }
            }
        }

        for path in removed {
            report.did(format!("removed {}", path.display()));
        }
        run_if_present(
            "update-mime-database",
            &[data.join("mime").to_string_lossy().as_ref()],
            report,
        );
        run_if_present(
            "update-desktop-database",
            &[data.join("applications").to_string_lossy().as_ref()],
            report,
        );
        Ok(())
    }
}

// ===========================================================================
// macOS
// ===========================================================================

#[cfg(target_os = "macos")]
mod platform {
    use super::*;
    use std::process::Command;

    fn app_dir() -> Result<PathBuf> {
        Ok(dirs::home_dir()
            .context("cannot determine the home directory")?
            .join("Applications")
            .join("Hermes.app"))
    }

    /// `CFBundleDocumentTypes` binds the extensions to the bundle; the
    /// `UTExportedTypeDeclarations` block is what makes Finder show our icon
    /// for the type rather than a generic document.
    fn info_plist() -> String {
        format!(
            r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Hermes</string>
  <key>CFBundleDisplayName</key><string>HERMES</string>
  <key>CFBundleIdentifier</key><string>dev.hermes.cli</string>
  <key>CFBundleVersion</key><string>{version}</string>
  <key>CFBundleShortVersionString</key><string>{version}</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>hermes-launcher</string>
  <key>CFBundleIconFile</key><string>hermes</string>
  <key>LSMinimumSystemVersion</key><string>10.13</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSUIElement</key><false/>
  <key>CFBundleDocumentTypes</key>
  <array>
    <dict>
      <key>CFBundleTypeName</key><string>{DESC_ORIGIN}</string>
      <key>CFBundleTypeExtensions</key><array><string>origin</string></array>
      <key>CFBundleTypeIconFile</key><string>origin</string>
      <key>CFBundleTypeRole</key><string>Editor</string>
      <key>LSHandlerRank</key><string>Owner</string>
      <key>LSItemContentTypes</key><array><string>{UTI_ORIGIN}</string></array>
    </dict>
    <dict>
      <key>CFBundleTypeName</key><string>{DESC_FOILED}</string>
      <key>CFBundleTypeExtensions</key><array><string>foiled</string></array>
      <key>CFBundleTypeIconFile</key><string>foiled</string>
      <key>CFBundleTypeRole</key><string>Viewer</string>
      <key>LSHandlerRank</key><string>Owner</string>
      <key>LSItemContentTypes</key><array><string>{UTI_FOILED}</string></array>
    </dict>
  </array>
  <key>UTExportedTypeDeclarations</key>
  <array>
    <dict>
      <key>UTTypeIdentifier</key><string>{UTI_ORIGIN}</string>
      <key>UTTypeDescription</key><string>{DESC_ORIGIN}</string>
      <key>UTTypeIconFile</key><string>origin</string>
      <key>UTTypeConformsTo</key><array><string>public.json</string></array>
      <key>UTTypeTagSpecification</key>
      <dict><key>public.filename-extension</key><array><string>origin</string></array></dict>
    </dict>
    <dict>
      <key>UTTypeIdentifier</key><string>{UTI_FOILED}</string>
      <key>UTTypeDescription</key><string>{DESC_FOILED}</string>
      <key>UTTypeIconFile</key><string>foiled</string>
      <key>UTTypeConformsTo</key><array><string>public.json</string></array>
      <key>UTTypeTagSpecification</key>
      <dict><key>public.filename-extension</key><array><string>foiled</string></array></dict>
    </dict>
  </array>
</dict>
</plist>
"#,
            version = env!("CARGO_PKG_VERSION")
        )
    }

    /// A double-clicked document needs a terminal: the consent prompt in
    /// Module 3 is interactive by design. The launcher hands the file to
    /// Terminal.app running the real binary.
    fn launcher_script(exe: &Path) -> String {
        format!(
            r#"#!/bin/sh
# Generated by `hermes install-system`. Opens Terminal.app so the interactive
# permission prompt is visible; the real work happens in the Rust binary.
HERMES="{exe}"
if [ "$#" -eq 0 ]; then
  osascript -e "tell application \"Terminal\" to do script \"'$HERMES' list\"" \
            -e 'tell application "Terminal" to activate'
  exit 0
fi
for arg in "$@"; do
  osascript -e "tell application \"Terminal\" to do script \"'$HERMES' open '$arg' --from-shell\"" \
            -e 'tell application "Terminal" to activate'
done
"#,
            exe = exe.display()
        )
    }

    pub fn install(exe: &Path, icons: &Path, report: &mut Report) -> Result<()> {
        let app = app_dir()?;
        let contents = app.join("Contents");
        let macos = contents.join("MacOS");
        let resources = contents.join("Resources");
        fs::create_dir_all(&macos)?;
        fs::create_dir_all(&resources)?;

        fs::write(contents.join("Info.plist"), info_plist())?;
        fs::write(contents.join("PkgInfo"), "APPL????")?;

        for name in ["origin.icns", "foiled.icns", "hermes.icns"] {
            fs::copy(icons.join(name), resources.join(name))
                .with_context(|| format!("copying {name} into the bundle"))?;
        }

        let launcher = macos.join("hermes-launcher");
        fs::write(&launcher, launcher_script(exe))?;
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&launcher, fs::Permissions::from_mode(0o755))?;
        }
        report.did(format!("built {}", app.display()));

        // Bump the bundle's mtime and re-register so Launch Services picks up
        // the new document types immediately.
        let _ = Command::new("touch").arg(&app).status();
        let lsregister = "/System/Library/Frameworks/CoreServices.framework/Frameworks/\
                          LaunchServices.framework/Support/lsregister";
        match Command::new(lsregister).arg("-f").arg(&app).status() {
            Ok(status) if status.success() => report.did("registered with Launch Services"),
            _ => report.warn(
                "could not run lsregister - the icons may take a minute (or a Finder restart) \
                 to appear"
                    .to_string(),
            ),
        }
        Ok(())
    }

    pub fn uninstall(report: &mut Report) -> Result<()> {
        let app = app_dir()?;
        if app.exists() {
            let lsregister = "/System/Library/Frameworks/CoreServices.framework/Frameworks/\
                              LaunchServices.framework/Support/lsregister";
            let _ = Command::new(lsregister).arg("-u").arg(&app).status();
            fs::remove_dir_all(&app)
                .with_context(|| format!("removing {}", app.display()))?;
            report.did(format!("removed {}", app.display()));
        }
        Ok(())
    }
}

// ===========================================================================
// Anything else
// ===========================================================================

#[cfg(not(any(windows, target_os = "linux", target_os = "macos")))]
mod platform {
    use super::*;

    pub fn install(_exe: &Path, _icons: &Path, report: &mut Report) -> Result<()> {
        report.warn(format!(
            "file associations are not implemented for {} - `hermes add <file>` still works",
            std::env::consts::OS
        ));
        Ok(())
    }

    pub fn uninstall(_report: &mut Report) -> Result<()> {
        Ok(())
    }
}
